services:
    php:
        build:
            dockerfile: php.Dockerfile
            context: .
        volumes:
            - .:/opt/project
            - ../computable:/data/computable
        tty: true
        user: 1000:1000

    redocly:
        image: redocly/cli:1.33.1
        volumes:
            - ..:/spec
        tty: true
        user: 1000:1000
        environment:
            REDOCLY_TELEMETRY: off
            NODE_OPTIONS: "--max-old-space-size=4048"

    swagger-cli:
        build:
            dockerfile: swagger-cli.Dockerfile
            context: .
        volumes:
            - ..:/data
        tty: true
        user: 1000:1000
