openapi: 3.0.3
info:
  title: Demographic API
  version: latest
  x-status: DRAFT
  x-spec: ehr
  contact:
    name: Specifications Editorial Committee openEHR
    url: 'https://specifications.openehr.org/'
    email: info@openehr.org
  license:
    name: Creative Commons Attribution-NoDerivs 3.0 Unported
    url: 'https://creativecommons.org/licenses/by-nd/3.0/'
  #description:
  #  $ref: ./docs/ehr/Intro.md
servers:
  - url: 'https://{baseUrl}/v1'
    description: An example openEHR server URL.
    variables:
      baseUrl:
        default: openEHRSys.example.com
        description: The (example) server base URL prefix providing openEHR services. This may contain server name, port and base path prefix.
security: []
paths:
  '/demographic/person':
    post:
      $ref: ./operations/person_create.yaml
  '/demographic/person/{uid_based_id}':
    get:
      $ref: ./operations/person_get.yaml
    put:
      $ref: ./operations/person_update.yaml
    delete:
      $ref: ./operations/person_delete.yaml
  '/demographic/versioned_person/{versioned_object_uid}':
    get:
      $ref: ./operations/versioned_person_get.yaml
  '/demographic/versioned_person/{versioned_object_uid}/revision_history':
    get:
      $ref: ./operations/versioned_person_revision_history.yaml
  '/demographic/versioned_person/{versioned_object_uid}/version':
    get:
      $ref: ./operations/versioned_person_version_get_at_time.yaml
  '/demographic/versioned_person/{versioned_object_uid}/version/{version_uid}':
    get:
      $ref: ./operations/versioned_person_version_get_by_id.yaml
  '/demographic/contribution':
    post:
      $ref: ./operations/contribution_create.yaml
  '/demographic/contribution/{contribution_uid}':
    get:
      $ref: ./operations/contribution_get.yaml
tags:
  - name: PERSON
    description: |
      Management of the [PERSON](https://specifications.openehr.org/releases/RM/latest/demographic.html#_person_class) and the associated [VERSIONED_PERSON](https://specifications.openehr.org/releases/RM/latest/demographic.html#_versioned_party_class) resource.
  - name: CONTRIBUTION
    description: |
      Management of [CONTRIBUTION](https://specifications.openehr.org/releases/RM/latest/common.html#_contribution_class) resource.
components:
  schemas:
    UAbstractItemStructure:
      $ref: ./schemas/data_structures/UAbstractItemStructure.yaml
